
export const paths = {
  home: '/',
  about: '/about',
  features: '/features',
  pricing: '/pricing',
  faq: '/faq',
  contact: '/contact',
  blog: '/blog',
  blogPost: '/blog/:postId',
  termsAndConditions: '/terms-and-conditions',
  dashboard: '/dashboard',
  components: {
    demoButton: '/components/demo-button',
    demoCard: '/components/demo-card',
    demoChart: '/components/demo-chart',
    demoDialog: '/components/demo-dialog',
    demoDropdown: '/components/demo-dropdown',
    demoForm: '/components/demo-form',
    demoTabs: '/components/demo-tabs',
    demoToggle: '/components/demo-toggle',
    demoTooltip: '/components/demo-tooltip',
  },
  colorPalette: '/color-palette',
  statusBoard: '/status-board',
  notFound: '*',
};