name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTHOR_NAME: ''
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Commit Author
        id: check-author
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "AUTHOR_NAME=$AUTHOR" >> $GITHUB_ENV
          if [ "$AUTHOR" = "Monorail Updater" ]; then
            echo "Commit author is Monorail Updater. Exiting..."
            exit 0
          fi

      # Set up Node.js
      - name: Setup Node.js
        if: env.AUTHOR_NAME != 'Monorail Updater'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install pnpm
      - name: Install pnpm
        if: env.AUTHOR_NAME != 'Monorail Updater'
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0

      # Cache pnpm dependencies
      - name: Cache pnpm dependencies
        if: env.AUTHOR_NAME != 'Monorail Updater'
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Prune pnpm store
        if: env.AUTHOR_NAME != 'Monorail Updater'
        run: pnpm store prune

      - name: Install dependencies
        if: env.AUTHOR_NAME != 'Monorail Updater'
        run: |
          retry() {
            for i in {1..3}; do
              "$@" && break || {
                echo "Retrying in 10 seconds..."
                sleep 10
              }
            done
          }
          retry pnpm install --frozen-lockfile

      - name: Build project
        if: env.AUTHOR_NAME != 'Monorail Updater'
        run: |
          export BASE_URL='/react-weapons-of-choice/'
          export DEBUG='true'
          pnpm exec nx build demo --configuration=production --base=$BASE_URL

      - name: Build storybook
        if: env.AUTHOR_NAME != 'Monorail Updater'
        run: |
          export BASE_URL='/react-weapons-of-choice/'
          export DEBUG='true'
          pnpm exec nx build-storybook storybook-host

      # Upload artifact for deployment
      - name: Upload to GitHub Pages artifact
        if: env.AUTHOR_NAME != 'Monorail Updater'
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/apps/demo # Path to your build output

  # Deploy step (separate job for GitHub Pages deployment)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # Required for deployment to GitHub Pages
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        if: env.AUTHOR_NAME != 'Monorail Updater'
        uses: actions/deploy-pages@v1
