name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm@9.12.2

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Prune pnpm store
        run: pnpm store prune

      - name: Install dependencies
        run: |
          retry() {
            for i in {1..3}; do
              "$@" && break || {
                echo "Retrying in 10 seconds..."
                sleep 10
              }
            done
          }
          retry pnpm install --frozen-lockfile

      - name: Build project
        run: |
          export BASE_URL='/react-weapons-of-choice/'
          pnpm exec nx build demo --configuration=production

      # Upload artifact for deployment
      - name: Upload to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/apps/demo # Path to your build output

  # Deploy step (separate job for GitHub Pages deployment)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # Required for deployment to GitHub Pages
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
