name: Lighthouse Badges

on:
  workflow_run:
    workflows: ['Deploy to GitHub Pages']
    types:
      - completed
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: write # Needed to push changes back to the repo

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-app-token
        uses: getsentry/action-github-app-token@v1.0.6
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-app-token.outputs.token }}

      - name: Check commit author
        id: check-author
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          if [ "$AUTHOR" = "Monorail Updater" ]; then
            echo "Commit made by Monorail Updater, exiting..."
            exit 1
          fi
        continue-on-error: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0

      - name: Install dependencies
        run: pnpm install

      - name: Generate Lighthouse badges
        run: pnpx lighthouse-badges --url='https://cambridgemonorail.github.io/react-weapons-of-choice/' --output-path='./lighthouse-badges'

      - name: Configure Git
        run: |
          git config user.name "Monorail Updater"
          git config user.email "monorail-updater@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add ./lighthouse-badges/*
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update Lighthouse badges"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ steps.generate-app-token.outputs.token }}
